version: '3.5'

services:

  # PostreSQL
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - rover-network

  # Liquibase
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: liquibase
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/changeLog:/liquibase/changelog
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/storage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_CHANGELOG=/liquibase/changelog/changeLog.xml
      - CLASSPATH=/liquibase/changelog
    command:
      - --changeLogFile=changeLog.xml
      - --url=jdbc:postgresql://postgres:5432/storage
      - --username=root
      - --password=root
      - update
    networks:
      - rover-network

  # Spring boot application
  rover:
    container_name: rover
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - rover-network
    restart: on-failure

# Docker containers network (name attribute is needed!)
networks:
  rover-network:
    name: rover-network
    driver: bridge
