services:

  # PostreSQL
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  # Liquibase
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: liquibase
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/changeLog:/liquibase/changelog
    environment:
      - DATABASE_URL=jdbc:postgresql://127.0.0.1:5432/storage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_CHANGELOG=/liquibase/changelog/changeLog.xml
      - CLASSPATH=/liquibase/changelog
    command:
      - --changeLogFile=changeLog.xml
      - --url=jdbc:postgresql://postgres:5432/storage
      - --username=root
      - --password=root
      - update