server:
  port: '8080'

spring:
  datasource-postgres:
    username: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/storage
    password: root
  datasource:
    postgres:
      hikari:
        maxLifetime: '1800000'
        connectionTimeout: '30000'
        idleTimeout: '600000'
  profiles:
    active: docker